apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployreactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myreactapp
  template:
    metadata:
      name: testpod1
      labels:
        app: myreactapp
    spec:
      containers:
        - name: c00
          image: shettyadarsha/my-react-app:latest
          ports:
           - containerPort: 3000
