apiVersion: v1 
kind: Secret 
metadata: 
  name: mongodb-secret 
type: Opaque 
data: 
  mongo-root-username: dXNlcm5hbWU=   # Base64 encoded $ echo -n 'username' | base64
  monog-root-password: cGFzc3dvcmQ=   # Base64 encoded $ echo -n 'password' | base64   
